title: "CS Teaching Track without a Ph.D"
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
search_enabled: false
collections:
  - people
  - career-path
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: people
    values:
      layout: person

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
